### ISSUE TITLE
Allow support for external class props

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [chronotruck/vue-ctk-date-time-picker#193] opened 2019-07-31 10:33 UTC
Hi It will be more flexible if you can add class props support like
`<date-time-picker v-model="startDate" :format="datePickerOptions_" :class="myexternalclass"></date-time-picker>`

**Comment by WilliamDASILVA** [comment] 2019-10-18 08:16
Hello,

Thank you for taking the time to make this issue. I think you're trying to customize the calendar but struggle with the current classes? If so, I'm considering this as duplicate of #149 .
Poke me if I'm wrong.

**Closed by WilliamDASILVA** 2019-10-18 08:16 UTC
Labels: duplicate
